version: 1
disable_existing_loggers: False
filters:
info_filter:
'()': filters.InfoOnlyFilter
formatters:
simple:
format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
console:
class: logging.StreamHandler
level: INFO
formatter: simple
filters: [info_filter]
stream: ext://sys.stdout
file:
class: logging.FileHandler

level: DEBUG
formatter: simple
filename: app.log
mode: a
loggers:
app_logger:
level: DEBUG
handlers: [console, file]
propagate: no
root:
level: WARNING
handlers: [console]

filters.py

import logging
class InfoOnlyFilter(logging.Filter):
def filter(self, record):
return record.levelno == logging.INFO